### ISSUE TITLE
DeadKeyFix won't run on HexChat 2.16

### ISSUE THREAD

**Issue by chiphead2332** [Xesyto/Hexchat-DeadKeyFix#6]
I get the following message on startup:

```
 Python interface loaded
 Failed to load module: 'charmap' codec can't decode byte 0x81 in position 561: character maps to <undefined>
 Traceback (most recent call last):
   File "<init code for '_hexchat_embedded'>", line 150, in loadfile
   File "C:\Program Files\Python36\Lib\encodings\cp1252.py", line 23, in decode
     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
 UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 561: character maps to <undefined>
```

**Comment by Stefan-v-Oudenaarden** [comment]
I'm sorry but i've not even opened an irc client in the last 2 years.
